my_app_user_skill:
    resource: "@MyAppUserBundle/Resources/config/routing/skill.yml"
    prefix:   /skill

front_page_home:
    path:     /hall
    defaults: { _controller: MyAppUserBundle:Home:hall }
messages:
    path:     /messages
    defaults: { _controller: MyAppUserBundle:Messages:index }
compose_message:
    path:     /compose
    defaults: { _controller: MyAppUserBundle:Messages:compose }

compose_message:
    path:     /compose
    defaults: { _controller: MyAppUserBundle:Messages:compose }

myProfile:
    path:     /profile
    defaults: { _controller: MyAppUserBundle:Profile:index }

EditProfile:
    path:     /profile/edit
    defaults: { _controller: MyAppUserBundle:Profile:Edit }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
pdf:
    path:     /pdf
    defaults: { _controller: MyAppUserBundle:Profile:toPdf }

